version: '3.9'

networks:
  web:
    external: true

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    env_file: .env
    expose:
      - '80'
    networks:
      - web
    labels:
      # Caddy labels
      caddy: "${AMPACHE_HOST}"
      caddy.reverse_proxy: "{{upstreams 80}}"
      # Traefik labels
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${AMPACHE_HOST}"
      traefik.port: '80'
    volumes:
      - ./docker-volumes/ampache/config:/var/www/config
      - ./docker-volumes/ampache/log:/var/log/ampache
      - ./docker-volumes/ampache/media:/media
      - ./docker-volumes/ampache/mysql:/var/lib/mysql
