version: '3.9'

networks:
  web:
    external: true
  ampache-net:
    driver: bridge

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    env_file: .env
    expose:
      - '80'
    networks:
      - web
      - ampache-net
    labels:
      caddy: "${AMPACHE_HOST}"
      caddy.reverse_proxy: "{{upstreams 80}}"
      traefik.enable: 'true'
      traefik.frontend.rule: "Host:${AMPACHE_HOST}"
      traefik.port: '80'
    volumes:
      - ./docker-volumes/ampache/config:/var/www/config
      - ./docker-volumes/ampache/log:/var/log/ampache
      - ./docker-volumes/ampache/media:/media
      - ./docker-volumes/ampache/mysql:/var/lib/mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    container_name: ampache-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - ampache-net
    volumes:
      - ./docker-volumes/ampache/mysql:/var/lib/mysql
