version: '3.9'

networks:
  web:
    external: true
  ampache-net:
    driver: bridge

services:
  ampache:
    image: ampache/ampache:latest
    container_name: ampache
    restart: unless-stopped
    env_file: .env
    expose:
      - 80
    networks:
      - web
      - ampache-net
    volumes:
      - ./docker-volumes/ampache/config:/var/www/config
      - ./docker-volumes/ampache/log:/var/log/ampache
      - ./docker-volumes/ampache/media:/media
    labels:
      caddy: "${AMPACHE_HOST}"
      caddy.reverse_proxy: "{{upstreams 80}}"
      traefik.enable: "true"
      traefik.frontend.rule: "Host:${AMPACHE_HOST}"
      traefik.port: "80"

  mysql:
    image: mysql:5.7
    container_name: ampache-mysql
    restart: unless-stopped
    env_file: .env
    networks:
      - ampache-net
    volumes:
      - ./docker-volumes/ampache/mysql:/var/lib/mysql
    expose:
      - 3306
